### ISSUE TITLE
Purge cloudflare cache

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMkart#4]
Fylkeskontaker og URG oppdaterer kartet, og anser det som feil når kartet ikke blir oppdatert med en gang. I dag caches filen av cloudflare, så denne bør tømmes ved kart update.

https://api.cloudflare.com/#zone-purge-individual-files-by-url-and-cache-tags

$ curl -X DELETE "https://api.cloudflare.com/client/v4/zones/023e105f4ecef8ad9ca31a8372d0c353/purge_cache" \
-H "X-Auth-Email: user@example.com" \
-H "X-Auth-Key: c2547eb745079dac9320b638f5e225cf483cc5cfdda41" \
-H "Content-Type: application/json" \
--data '{"files":["http://www.example.com/css/styles.css"],"tags":["some-tag","another-tag"]}'

**Comment by mariusmandal** [comment]
@AsgeirSH check this one out

**Comment by AsgeirSH** [comment]
Fixed!
